@startuml sd_design_main

Main  -> EchGenerator : generate_ech(reseau,TS,mode)
Main <-- EchGenerator : ECH

Main  -> SequenceGenerator : generate_sequence(reseau,TS,mode,ECH)
Main <-- SequenceGenerator : Sequence

Main  -> SequenceLauncher : launch(sequence, session, initialSituation, uncertainties, assessmentUncertainties)
note right
    Session : Réseau, TS, ECH
end note
Main <-- SequenceLauncher

@enduml
